# Generated by Django 4.2.7 on 2025-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appNotification', '0003_news_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(default='None', max_length=20, unique=True),
        ),
    ]
